# ==============================================================================
# File: services/actions/coding_assist.py
# Project: J.A.R.V.I.S. - Just A Rather Very Intelligent System
# ==============================================================================
#
# Description:
#    Coding Assistant Orchestrator
#
#    - High-level coding workflow automation for project scaffolding.
#    - Uses FileController + CmdControl for deterministic file and shell actions.
#    - Supports creating small/medium starter projects and multi-file writes.
#    - Returns structured payloads suitable for agent synthesis.
#
# Author: Deepak Rakshit
# Repository: https://github.com/deepakrakshit/jarvis
#
# Copyright (c) 2025 Deepak Rakshit. All rights reserved.
# See LICENSE file in the project root for license information.
# ==============================================================================

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path, PurePosixPath
import re
from textwrap import dedent
from typing import Any

from core.llm_api import chat_complete
from core.settings import AppConfig
from services.actions.file_controller import FileController, file_control_action
from services.system.cmd_control import CmdControl, cmd_control_action


def _block(text: str) -> str:
    return dedent(text).strip() + "\n"


@dataclass(frozen=True)
class ProjectTemplate:
    kind: str
    files: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class GeneratedProjectBundle:
    files: tuple[tuple[str, str], ...]
    summary: str


class CodingAssistService:
    """Production-focused coding workflow helper."""

    _DEFAULT_PROJECTS_DIR = "Projects"
    _PROJECT_TYPE_ALIASES: dict[str, str] = {
        "python": "python-cli",
        "py": "python-cli",
        "python-project": "python-cli",
        "python app": "python-cli",
        "python script": "python-cli",
        "cli": "python-cli",
        "command-line": "python-cli",
        "command line": "python-cli",
        "api": "fastapi-service",
        "fastapi": "fastapi-service",
        "fastapi api": "fastapi-service",
        "backend": "fastapi-service",
        "service": "fastapi-service",
        "web-api": "fastapi-service",
    }
    _MAX_GENERATED_FILES = 28
    _MAX_GENERATED_FILE_BYTES = 140_000

    _TEMPLATES: dict[str, ProjectTemplate] = {
        "python-cli": ProjectTemplate(
            kind="python-cli",
            files=(
                (
                    "README.md",
                    _block(
                        """
                        # Python CLI Starter

                        Production-ready modular Python CLI scaffold generated by JARVIS.

                        ## Quick Start
                        1. python -m pip install -e .
                        2. python -m app.cli --help
                        """
                    ),
                ),
                (
                    "pyproject.toml",
                    _block(
                        """
                        [build-system]
                        requires = ["setuptools>=68", "wheel"]
                        build-backend = "setuptools.build_meta"

                        [project]
                        name = "jarvis-cli-project"
                        version = "0.1.0"
                        description = "Production-ready Python CLI starter"
                        requires-python = ">=3.10"
                        dependencies = []

                        [project.optional-dependencies]
                        dev = [
                          "pytest>=8.0.0",
                          "mypy>=1.9.0",
                          "ruff>=0.5.0",
                        ]

                        [tool.setuptools.packages.find]
                        where = ["src"]

                        [tool.pytest.ini_options]
                        testpaths = ["tests"]
                        python_files = ["test_*.py"]

                        [tool.mypy]
                        python_version = "3.10"
                        warn_unused_configs = true
                        disallow_untyped_defs = true
                        check_untyped_defs = true

                        [tool.ruff]
                        line-length = 100
                        target-version = "py310"
                        """
                    ),
                ),
                (
                    "requirements.txt",
                    "",
                ),
                (
                    ".gitignore",
                    _block(
                        """
                        __pycache__/
                        *.py[cod]
                        *$py.class
                        .env
                        .venv/
                        env/
                        venv/
                        .pytest_cache/
                        .coverage
                        .mypy_cache/
                        .ruff_cache/
                        dist/
                        build/
                        *.egg-info/
                        """
                    )
                ),
                (
                    ".env.example",
                    _block(
                        """
                        # Environment variables template
                        LOG_LEVEL=INFO
                        PORT=8000
                        """
                    )
                ),
                (
                    "src/app/__init__.py",
                    _block(
                        """
                        from .cli import run

                        __all__ = ["run"]
                        """
                    ),
                ),
                (
                    "src/app/cli.py",
                    _block(
                        """
                        from __future__ import annotations

                        import argparse
                        import io
                        import sys


                        def _build_parser() -> argparse.ArgumentParser:
                            parser = argparse.ArgumentParser(description="Production-ready Python CLI starter")
                            parser.add_argument("--name", default="World", help="Name to greet")
                            return parser


                        def run(argv: list[str] | None = None, *, stdout: io.TextIOBase | None = None) -> int:
                            parser = _build_parser()
                            args = parser.parse_args(argv)
                            print(f"Hello, {args.name}!", file=stdout or sys.stdout)
                            return 0


                        def main() -> None:
                            raise SystemExit(run())


                        if __name__ == "__main__":
                            main()
                        """
                    ),
                ),
                (
                    "tests/test_cli.py",
                    _block(
                        """
                        from __future__ import annotations

                        import io
                        import sys
                        import unittest
                        from pathlib import Path

                        ROOT = Path(__file__).resolve().parents[1]
                        SRC = ROOT / "src"
                        if str(SRC) not in sys.path:
                            sys.path.insert(0, str(SRC))

                        from app.cli import run


                        class CliTests(unittest.TestCase):
                            def test_run_prints_expected_message(self) -> None:
                                out = io.StringIO()
                                code = run(["--name", "Tester"], stdout=out)
                                self.assertEqual(code, 0)
                                self.assertEqual(out.getvalue().strip(), "Hello, Tester!")


                        if __name__ == "__main__":
                            unittest.main()
                        """
                    ),
                ),
            ),
        ),
        "fastapi-service": ProjectTemplate(
            kind="fastapi-service",
            files=(
                (
                    "README.md",
                    _block(
                        """
                        # FastAPI Service

                        Production-grade FastAPI scaffold generated by JARVIS.

                        ## Run
                        1. pip install -r requirements.txt
                        2. uvicorn app.main:app --reload
                        """
                    ),
                ),
                (
                    "pyproject.toml",
                    _block(
                        """
                        [build-system]
                        requires = ["setuptools>=68", "wheel"]
                        build-backend = "setuptools.build_meta"

                        [project]
                        name = "jarvis-fastapi-service"
                        version = "0.1.0"
                        description = "Production-ready FastAPI starter"
                        requires-python = ">=3.10"

                        [tool.pytest.ini_options]
                        testpaths = ["tests"]
                        python_files = ["test_*.py"]
                        """
                    ),
                ),
                (
                    "requirements.txt",
                    "fastapi\nuvicorn[standard]\nhttpx\n",
                ),
                (
                    ".gitignore",
                    _block(
                        """
                        __pycache__/
                        *.py[cod]
                        *$py.class
                        .env
                        .venv/
                        env/
                        venv/
                        .pytest_cache/
                        .coverage
                        .mypy_cache/
                        .ruff_cache/
                        """
                    )
                ),
                (
                    ".env.example",
                    _block(
                        """
                        # Enterprise FastAPI Environment Variables
                        LOG_LEVEL=INFO
                        API_ENV=development
                        DB_HOST=localhost
                        DB_PORT=5432
                        DB_USER=postgres
                        DB_PASS=secret
                        """
                    )
                ),
                (
                    "app/main.py",
                    _block(
                        """
                        from __future__ import annotations

                        from fastapi import FastAPI
                        from app.routes import router

                        app = FastAPI(title="Service API", version="1.0.0")
                        app.include_router(router)


                        @app.get("/health")
                        def health() -> dict[str, str]:
                            return {"status": "ok"}
                        """
                    ),
                ),
                (
                    "app/routes.py",
                    _block(
                        """
                        from __future__ import annotations

                        from fastapi import APIRouter

                        router = APIRouter(prefix="/api")


                        @router.get("/ping")
                        def ping() -> dict[str, str]:
                            return {"message": "pong"}
                        """
                    ),
                ),
                (
                    "tests/test_health.py",
                    _block(
                        """
                        from __future__ import annotations

                        from fastapi.testclient import TestClient

                        from app.main import app


                        def test_health() -> None:
                            client = TestClient(app)
                            response = client.get("/health")
                            assert response.status_code == 200
                            assert response.json() == {"status": "ok"}
                        """
                    ),
                ),
            ),
        ),
    }

    def __init__(self, *, workspace_root: str, config: AppConfig | None = None) -> None:
        self._workspace_root = Path(workspace_root).resolve()
        self._file_controller = FileController(workspace_root=str(self._workspace_root))
        self._cmd_controller = CmdControl(workspace_root=str(self._workspace_root))
        self._config = config

    def create_project(
        self,
        *,
        name: str,
        project_type: str = "python-cli",
        target_dir: str = _DEFAULT_PROJECTS_DIR,
        objective: str = "",
        prompt: str = "",
        open_after_create: bool = True,
    ) -> dict[str, Any]:
        normalized_name = self._sanitize_project_name(name)
        if not normalized_name:
            return self._error("invalid_project_name", "Project name is empty or invalid.")

        objective_text = self._compose_project_objective(
            project_name=normalized_name,
            requested_project_type=project_type,
            objective=objective,
            prompt=prompt,
        )
        requested_project_type = str(project_type or "").strip()
        resolved_project_type = self._normalize_project_type(requested_project_type, objective_text)
        fallback_template = self._resolve_fallback_template(resolved_project_type, objective_text)

        # Keep calculator scaffolds deterministic and enterprise-grade.
        prefer_deterministic_template = (
            resolved_project_type == "python-cli" and "calculator" in objective_text.lower()
        )
        generated_bundle: GeneratedProjectBundle | None = None
        if not prefer_deterministic_template:
            generated_bundle = self._generate_project_with_gemini(
                project_name=normalized_name,
                resolved_project_type=resolved_project_type,
                objective=objective_text,
                fallback_template=fallback_template,
            )

        generator = "gemini" if generated_bundle is not None else "template"
        generation_summary = generated_bundle.summary if generated_bundle is not None else ""
        files_to_create = generated_bundle.files if generated_bundle is not None else fallback_template.files

        project_parent = self._resolve_target_root(target_dir or self._DEFAULT_PROJECTS_DIR)
        root = project_parent / normalized_name
        mkdir_result = self._file_controller.make_directory(path=str(root), exist_ok=True)
        if not bool(mkdir_result.get("success")):
            return mkdir_result

        created_files: list[str] = []
        open_result: dict[str, Any] | None = None
        for relative_path, content in files_to_create:
            file_path = root / relative_path
            write_result = self._file_controller.write_text(
                path=str(file_path),
                content=content,
                append=False,
                create_parents=True,
            )
            if not bool(write_result.get("success")):
                return self._error(
                    "project_generation_failed",
                    f"Failed while writing {relative_path}",
                    details={
                        "partial_files": created_files,
                        "failure": write_result,
                        "generator": generator,
                        "resolved_project_type": resolved_project_type,
                    },
                )
            created_files.append(str(file_path))

        if open_after_create:
            try:
                open_result = self._file_controller.open_path(path=str(root))
            except Exception as exc:
                open_result = {
                    "status": "error",
                    "action": "open",
                    "success": False,
                    "verified": False,
                    "error": "open_failed",
                    "message": f"Open project failed: {exc}",
                }

        opened = bool(open_result and open_result.get("success"))
        open_suffix = " and opened" if opened else ""

        return {
            "status": "success",
            "action": "create_project",
            "success": True,
            "verified": True,
            "error": "",
            "message": (
                f"Project '{normalized_name}' created as '{resolved_project_type}' "
                f"using {generator} scaffolding{open_suffix}."
            ),
            "data": {
                "project_root": str(root),
                "projects_root": str(project_parent),
                "requested_project_type": requested_project_type or "auto",
                "project_type": resolved_project_type,
                "generator": generator,
                "objective": objective_text,
                "generation_summary": generation_summary,
                "opened": opened,
                "open_result": open_result or {},
                "created_files": created_files,
            },
        }

    def create_files(self, *, base_dir: str, files: list[dict[str, Any]]) -> dict[str, Any]:
        root = self._resolve_target_root(base_dir)
        write_results: list[dict[str, Any]] = []

        for item in files:
            if not isinstance(item, dict):
                continue
            rel_path = str(item.get("path") or "").strip()
            if not rel_path:
                continue
            content = str(item.get("content") or "")
            path = root / rel_path
            result = self._file_controller.write_text(
                path=str(path),
                content=content,
                append=False,
                create_parents=True,
            )
            write_results.append(result)

            if not bool(result.get("success")):
                return self._error(
                    "file_batch_failed",
                    "Failed during multi-file creation.",
                    details={"results": write_results},
                )

        return {
            "status": "success",
            "action": "create_files",
            "success": True,
            "verified": True,
            "error": "",
            "message": f"Created {len(write_results)} file(s).",
            "data": {"base_dir": str(root), "results": write_results},
        }

    def run_command(self, *, command: str, cwd: str | None = None, timeout_seconds: int = 90) -> dict[str, Any]:
        resolved_cwd = str((self._resolve_target_root(cwd or ".")).resolve())
        return self._cmd_controller.run(
            command=command,
            cwd=resolved_cwd,
            timeout_seconds=timeout_seconds,
            shell="cmd",
        )

    def run_file(self, *, file_path: str, cwd: str | None = None, timeout_seconds: int = 180) -> dict[str, Any]:
        candidate = self._resolve_target_root(file_path)
        if not candidate.exists() or not candidate.is_file():
            return self._error("file_not_found", f"Runnable file not found: {file_path}")

        run_command = self._build_file_execution_command(candidate)
        if not run_command:
            return self._error(
                "unsupported_file_type",
                f"I do not know how to run this file type yet: {candidate.suffix or '(no extension)'}",
            )

        resolved_cwd = str((self._resolve_target_root(cwd or str(candidate.parent))).resolve())
        cmd_result = self._cmd_controller.run(
            command=run_command,
            cwd=resolved_cwd,
            timeout_seconds=max(10, int(timeout_seconds or 180)),
            shell="cmd",
        )
        success = bool(cmd_result.get("success", False))

        return {
            "status": "success" if success else "error",
            "action": "run_file",
            "success": success,
            "verified": bool(cmd_result.get("verified", False)),
            "error": "" if success else str(cmd_result.get("error") or "run_file_failed"),
            "message": (
                f"Executed file {candidate.name} in terminal."
                if success
                else f"Failed to execute file {candidate.name}."
            ),
            "data": {
                "file_path": str(candidate),
                "cwd": resolved_cwd,
                "command": run_command,
                "terminal_result": cmd_result,
            },
        }

    def run_project(
        self,
        *,
        project_path: str = ".",
        command: str = "",
        open_folder: bool = False,
        timeout_seconds: int = 240,
        request: str = "",
    ) -> dict[str, Any]:
        root = self._resolve_target_root(project_path or ".")
        if not root.exists() or not root.is_dir():
            return self._error("project_not_found", f"Project directory not found: {project_path}")

        open_result: dict[str, Any] | None = None
        if open_folder:
            open_result = self._file_controller.open_path(path=str(root), query=request or str(root))

        normalized_request = " ".join(str(request or "").strip().split())
        run_command = " ".join(str(command or "").strip().split())
        if not run_command:
            run_command = self._infer_project_execution_command(root, normalized_request)
        if not run_command:
            return self._error(
                "project_run_command_not_found",
                "Could not infer a runnable project command. Provide command explicitly.",
                details={"project_path": str(root)},
            )

        cmd_result = self._cmd_controller.run(
            command=run_command,
            cwd=str(root.resolve()),
            timeout_seconds=max(15, int(timeout_seconds or 240)),
            shell="cmd",
        )
        success = bool(cmd_result.get("success", False))

        return {
            "status": "success" if success else "error",
            "action": "run_project",
            "success": success,
            "verified": bool(cmd_result.get("verified", False)),
            "error": "" if success else str(cmd_result.get("error") or "run_project_failed"),
            "message": (
                f"Executed project command in {root.name}: {run_command}"
                if success
                else f"Failed to execute project command in {root.name}."
            ),
            "data": {
                "project_path": str(root),
                "command": run_command,
                "open_result": open_result or {},
                "terminal_result": cmd_result,
            },
        }

    def run_from_request(
        self,
        *,
        request: str,
        cwd: str | None = None,
        open_folder: bool = True,
        timeout_seconds: int = 240,
    ) -> dict[str, Any]:
        request_text = " ".join(str(request or "").strip().split())
        if not request_text:
            return self._error("missing_request", "run_from_request requires a request string.")

        working_dir = self._resolve_target_root(cwd) if str(cwd or "").strip() else self._infer_working_directory_from_request(request_text)
        if not working_dir.exists() or not working_dir.is_dir():
            return self._error(
                "invalid_cwd",
                f"Could not resolve a runnable working directory for: {request_text}",
            )

        open_result: dict[str, Any] | None = None
        if open_folder:
            open_result = self._file_controller.open_path(path=str(working_dir), query=request_text)

        explicit_command = self._extract_explicit_terminal_command(request_text)
        file_target = self._infer_file_target_from_request(request_text, working_dir)

        if explicit_command:
            run_command = explicit_command
            run_action = "run_command"
        elif file_target is not None:
            run_command = self._build_file_execution_command(file_target)
            run_action = "run_file"
        else:
            run_command = self._infer_project_execution_command(working_dir, request_text)
            run_action = "run_project"

        if not run_command:
            return self._error(
                "run_command_not_inferred",
                "I could not infer what to run. Provide an explicit command or file path.",
                details={"request": request_text, "working_dir": str(working_dir)},
            )

        cmd_result = self._cmd_controller.run(
            command=run_command,
            cwd=str(working_dir.resolve()),
            timeout_seconds=max(15, int(timeout_seconds or 240)),
            shell="cmd",
        )
        success = bool(cmd_result.get("success", False))
        return {
            "status": "success" if success else "error",
            "action": "run_from_request",
            "success": success,
            "verified": bool(cmd_result.get("verified", False)),
            "error": "" if success else str(cmd_result.get("error") or "run_from_request_failed"),
            "message": (
                f"Resolved and executed terminal workflow ({run_action})."
                if success
                else f"Resolved terminal workflow ({run_action}) but execution failed."
            ),
            "data": {
                "request": request_text,
                "cwd": str(working_dir.resolve()),
                "run_action": run_action,
                "command": run_command,
                "file_target": str(file_target) if file_target is not None else "",
                "open_result": open_result or {},
                "terminal_result": cmd_result,
            },
        }

    def compare_dependencies(
        self,
        *,
        requirements_path: str = "requirements.txt",
        setup_path: str = "setup.py",
        pyproject_path: str = "pyproject.toml",
    ) -> dict[str, Any]:
        requirements_file = self._resolve_target_root(requirements_path)
        setup_file = self._resolve_target_root(setup_path)
        pyproject_file = self._resolve_target_root(pyproject_path)

        if not requirements_file.exists() or not requirements_file.is_file():
            return self._error(
                "requirements_not_found",
                f"File not found: {requirements_path}",
            )

        try:
            requirements_text = requirements_file.read_text(encoding="utf-8")
        except Exception as exc:
            return self._error("requirements_read_failed", f"Could not read {requirements_path}: {exc}")

        requirements_deps = self._parse_dependency_names_from_requirements(requirements_text)

        reference_source = ""
        reference_path = ""
        reference_deps: set[str] = set()

        if setup_file.exists() and setup_file.is_file():
            try:
                setup_text = setup_file.read_text(encoding="utf-8")
                reference_deps = self._parse_dependency_names_from_setup(setup_text)
                reference_source = "setup.py"
                reference_path = str(setup_file)
            except Exception as exc:
                return self._error("setup_read_failed", f"Could not read {setup_path}: {exc}")
        elif pyproject_file.exists() and pyproject_file.is_file():
            try:
                pyproject_text = pyproject_file.read_text(encoding="utf-8")
                reference_deps = self._parse_dependency_names_from_pyproject(pyproject_text)
                reference_source = "pyproject.toml"
                reference_path = str(pyproject_file)
            except Exception as exc:
                return self._error("pyproject_read_failed", f"Could not read {pyproject_path}: {exc}")
        else:
            return self._error(
                "reference_dependencies_not_found",
                (
                    f"Neither {setup_path} nor {pyproject_path} was found. "
                    "Dependency comparison requires one reference dependency file."
                ),
            )

        only_in_requirements = sorted(requirements_deps - reference_deps)
        only_in_reference = sorted(reference_deps - requirements_deps)
        shared = sorted(requirements_deps & reference_deps)

        setup_missing = not setup_file.exists()
        if setup_missing and reference_source == "pyproject.toml":
            message = (
                "setup.py was not found. Compared requirements.txt against pyproject.toml instead and "
                f"found {len(only_in_requirements) + len(only_in_reference)} mismatch(es)."
            )
        else:
            message = (
                f"Compared requirements.txt against {reference_source} and found "
                f"{len(only_in_requirements) + len(only_in_reference)} mismatch(es)."
            )

        return {
            "status": "success",
            "action": "compare_dependencies",
            "success": True,
            "verified": True,
            "error": "",
            "message": message,
            "data": {
                "requirements_path": str(requirements_file),
                "reference_source": reference_source,
                "reference_path": reference_path,
                "requirements_dependencies": sorted(requirements_deps),
                "reference_dependencies": sorted(reference_deps),
                "only_in_requirements": only_in_requirements,
                "only_in_reference": only_in_reference,
                "shared_dependencies": shared,
                "mismatch_count": len(only_in_requirements) + len(only_in_reference),
            },
        }

    def plan(self, *, objective: str) -> dict[str, Any]:
        brief = " ".join(str(objective or "").split())
        if not brief:
            return self._error("missing_objective", "Coding objective is empty.")

        plan_steps = self._generate_plan_with_gemini(brief) or [
            "Clarify scope, NFRs, and interfaces.",
            "Define architecture boundaries and module ownership.",
            "Implement code, tests, and structured error handling.",
            "Run validation checks and address quality gaps.",
            "Document setup, operations, and extension paths.",
        ]
        return {
            "status": "success",
            "action": "plan",
            "success": True,
            "verified": True,
            "error": "",
            "message": "Generated coding plan.",
            "data": {
                "objective": brief,
                "steps": plan_steps,
            },
        }

    def _load_config(self) -> AppConfig | None:
        if self._config is not None:
            return self._config
        try:
            self._config = AppConfig.from_env(".env")
        except Exception:
            self._config = None
        return self._config

    def _normalize_project_type(self, project_type: str, objective: str) -> str:
        raw = " ".join(str(project_type or "").strip().lower().replace("_", "-").split())
        normalized_key = raw.replace("-", " ")

        if raw in self._TEMPLATES:
            return raw

        if normalized_key in self._PROJECT_TYPE_ALIASES:
            return self._PROJECT_TYPE_ALIASES[normalized_key]

        objective_lower = str(objective or "").lower()
        if any(token in objective_lower for token in ("fastapi", "api service", "rest api", "endpoint")):
            return "fastapi-service"

        return "python-cli"

    def _compose_project_objective(
        self,
        *,
        project_name: str,
        requested_project_type: str,
        objective: str,
        prompt: str,
    ) -> str:
        merged = " ".join(part.strip() for part in (objective, prompt) if str(part or "").strip())
        if merged:
            return merged

        normalized_type = self._normalize_project_type(requested_project_type, "")
        return (
            f"Create a production-ready {normalized_type} project named {project_name} "
            "with clean architecture, robust tests, and documentation."
        )

    def _resolve_fallback_template(self, project_type: str, objective: str) -> ProjectTemplate:
        if project_type == "python-cli":
            objective_lower = str(objective or "").lower()
            if "calculator" in objective_lower:
                return self._calculator_python_template()

        return self._TEMPLATES.get(project_type, self._TEMPLATES["python-cli"])

    def _calculator_python_template(self) -> ProjectTemplate:
        return ProjectTemplate(
            kind="python-cli",
            files=(
                (
                    "README.md",
                    _block(
                        """
                        # Calculator

                        Enterprise-grade modular calculator package generated by JARVIS.

                        ## Highlights
                        - Safe AST-based expression evaluation (no eval).
                        - Typed domain errors for clear operational handling.
                        - Precision-aware decimal math with configurable scale.
                        - Unit-tested engine and CLI entrypoint.

                        ## Quick Start
                        1. python -m pip install -e .
                        2. python -m calculator.cli "2 + 2 * 5" --scale 2
                        """
                    ),
                ),
                (
                    "pyproject.toml",
                    _block(
                        """
                        [build-system]
                        requires = ["setuptools>=68", "wheel"]
                        build-backend = "setuptools.build_meta"

                        [project]
                        name = "calculator"
                        version = "0.1.0"
                        description = "Enterprise-grade modular calculator"
                        requires-python = ">=3.10"
                        dependencies = []

                        [project.optional-dependencies]
                        dev = [
                          "pytest>=8.0.0",
                          "mypy>=1.9.0",
                          "ruff>=0.5.0",
                        ]

                        [tool.setuptools.packages.find]
                        where = ["src"]

                        [tool.pytest.ini_options]
                        testpaths = ["tests"]
                        python_files = ["test_*.py"]

                        [tool.mypy]
                        python_version = "3.10"
                        warn_unused_configs = true
                        disallow_untyped_defs = true
                        check_untyped_defs = true

                        [tool.ruff]
                        line-length = 100
                        target-version = "py310"
                        """
                    ),
                ),
                (
                    "requirements.txt",
                    "",
                ),
                (
                    "src/calculator/__init__.py",
                    _block(
                        """
                        from .engine import CalculatorEngine, EngineConfig
                        from .errors import (
                            CalculatorDivisionByZeroError,
                            CalculatorError,
                            CalculatorSyntaxError,
                            CalculatorValidationError,
                        )

                        __all__ = [
                            "CalculatorEngine",
                            "EngineConfig",
                            "CalculatorError",
                            "CalculatorSyntaxError",
                            "CalculatorValidationError",
                            "CalculatorDivisionByZeroError",
                        ]
                        """
                    ),
                ),
                (
                    "src/calculator/errors.py",
                    _block(
                        """
                        from __future__ import annotations


                        class CalculatorError(ValueError):
                            '''Base domain error for calculator failures.'''


                        class CalculatorSyntaxError(CalculatorError):
                            '''Raised when an expression cannot be parsed safely.'''


                        class CalculatorValidationError(CalculatorError):
                            '''Raised for input that violates validation policy.'''


                        class CalculatorDivisionByZeroError(CalculatorError):
                            '''Raised when division-by-zero is attempted.'''
                        """
                    ),
                ),
                (
                    "src/calculator/engine.py",
                    _block(
                        """
                        from __future__ import annotations

                        import ast
                        import re
                        from dataclasses import dataclass
                        from decimal import Decimal, DivisionByZero, InvalidOperation

                        from .errors import (
                            CalculatorDivisionByZeroError,
                            CalculatorSyntaxError,
                            CalculatorValidationError,
                        )


                        @dataclass(frozen=True)
                        class EngineConfig:
                            max_expression_length: int = 320
                            max_scale: int = 10


                        class CalculatorEngine:
                            def __init__(self, config: EngineConfig | None = None) -> None:
                                self._config = config or EngineConfig()

                            def evaluate(self, expression: str, *, scale: int = 4) -> Decimal:
                                normalized = self._normalize_expression(expression)
                                parsed = self._parse_expression(normalized)
                                raw_result = self._eval_node(parsed.body)
                                safe_scale = self._validate_scale(scale)
                                quant = Decimal("1").scaleb(-safe_scale)
                                return raw_result.quantize(quant)

                            def _normalize_expression(self, expression: str) -> str:
                                text = str(expression or "").strip()
                                if not text:
                                    raise CalculatorValidationError("Expression is empty.")
                                if len(text) > self._config.max_expression_length:
                                    raise CalculatorValidationError("Expression is too long.")
                                if not re.fullmatch(r"[0-9+\\-*/().%\\s]+", text):
                                    raise CalculatorValidationError(
                                        "Expression contains unsupported characters."
                                    )
                                return text

                            def _parse_expression(self, expression: str) -> ast.Expression:
                                try:
                                    parsed = ast.parse(expression, mode="eval")
                                except SyntaxError as exc:
                                    raise CalculatorSyntaxError("Expression syntax is invalid.") from exc
                                if not isinstance(parsed, ast.Expression):
                                    raise CalculatorSyntaxError(
                                        "Only arithmetic expressions are allowed."
                                    )
                                return parsed

                            def _validate_scale(self, scale: int) -> int:
                                safe_scale = int(scale)
                                if safe_scale < 0 or safe_scale > self._config.max_scale:
                                    raise CalculatorValidationError(
                                        f"Scale must be between 0 and {self._config.max_scale}."
                                    )
                                return safe_scale

                            def _eval_node(self, node: ast.AST) -> Decimal:
                                if isinstance(node, ast.Constant):
                                    if isinstance(node.value, bool) or not isinstance(node.value, (int, float)):
                                        raise CalculatorSyntaxError(
                                            "Only numeric constants are supported."
                                        )
                                    return Decimal(str(node.value))

                                if isinstance(node, ast.UnaryOp):
                                    operand = self._eval_node(node.operand)
                                    if isinstance(node.op, ast.UAdd):
                                        return operand
                                    if isinstance(node.op, ast.USub):
                                        return -operand
                                    raise CalculatorSyntaxError("Unsupported unary operator.")

                                if isinstance(node, ast.BinOp):
                                    left = self._eval_node(node.left)
                                    right = self._eval_node(node.right)
                                    return self._apply_binary_operator(node.op, left, right)

                                raise CalculatorSyntaxError("Only arithmetic expressions are supported.")

                            def _apply_binary_operator(
                                self, op_node: ast.operator, left: Decimal, right: Decimal
                            ) -> Decimal:
                                try:
                                    if isinstance(op_node, ast.Add):
                                        return left + right
                                    if isinstance(op_node, ast.Sub):
                                        return left - right
                                    if isinstance(op_node, ast.Mult):
                                        return left * right
                                    if isinstance(op_node, ast.Div):
                                        if right == 0:
                                            raise CalculatorDivisionByZeroError(
                                                "Division by zero is not allowed."
                                            )
                                        return left / right
                                    if isinstance(op_node, ast.Mod):
                                        if right == 0:
                                            raise CalculatorDivisionByZeroError(
                                                "Modulo by zero is not allowed."
                                            )
                                        return left % right
                                    if isinstance(op_node, ast.Pow):
                                        if abs(right) > Decimal("12"):
                                            raise CalculatorValidationError("Exponent is too large.")
                                        return left**right
                                except DivisionByZero as exc:
                                    raise CalculatorDivisionByZeroError(
                                        "Division by zero is not allowed."
                                    ) from exc
                                except InvalidOperation as exc:
                                    raise CalculatorValidationError(
                                        "The operation produced an invalid numeric value."
                                    ) from exc

                                raise CalculatorSyntaxError("Unsupported binary operator.")
                        """
                    ),
                ),
                (
                    "src/calculator/cli.py",
                    _block(
                        """
                        from __future__ import annotations

                        import argparse
                        import io
                        import sys
                        from decimal import Decimal

                        from calculator.engine import CalculatorEngine
                        from calculator.errors import CalculatorError


                        def _build_parser() -> argparse.ArgumentParser:
                            parser = argparse.ArgumentParser(
                                description="Production-grade safe calculator CLI"
                            )
                            parser.add_argument("expression", nargs="*", help="Expression to evaluate")
                            parser.add_argument(
                                "--scale",
                                type=int,
                                default=4,
                                help="Decimal precision scale (0-10)",
                            )
                            return parser


                        def _format_decimal(value: Decimal) -> str:
                            text = format(value.normalize(), "f")
                            if "." in text:
                                text = text.rstrip("0").rstrip(".")
                            return text or "0"


                        def run(
                            argv: list[str] | None = None,
                            *,
                            stdout: io.TextIOBase | None = None,
                            stderr: io.TextIOBase | None = None,
                        ) -> int:
                            parser = _build_parser()
                            args = parser.parse_args(argv)
                            expression = " ".join(args.expression).strip()
                            if not expression:
                                parser.print_help(file=stderr or sys.stderr)
                                return 2

                            engine = CalculatorEngine()
                            try:
                                result = engine.evaluate(expression, scale=args.scale)
                                print(_format_decimal(result), file=stdout or sys.stdout)
                                return 0
                            except CalculatorError as exc:
                                print(f"Error: {exc}", file=stderr or sys.stderr)
                                return 1


                        def main() -> None:
                            raise SystemExit(run())


                        if __name__ == "__main__":
                            main()
                        """
                    ),
                ),
                (
                    "tests/test_engine.py",
                    _block(
                        """
                        from __future__ import annotations

                        import sys
                        import unittest
                        from decimal import Decimal
                        from pathlib import Path

                        ROOT = Path(__file__).resolve().parents[1]
                        SRC = ROOT / "src"
                        if str(SRC) not in sys.path:
                            sys.path.insert(0, str(SRC))

                        from calculator.engine import CalculatorEngine
                        from calculator.errors import (
                            CalculatorDivisionByZeroError,
                            CalculatorSyntaxError,
                            CalculatorValidationError,
                        )


                        class CalculatorTests(unittest.TestCase):
                            def setUp(self) -> None:
                                self.engine = CalculatorEngine()

                            def test_basic_math(self) -> None:
                                self.assertEqual(
                                    self.engine.evaluate("2 + 3 * 4", scale=0),
                                    Decimal("14"),
                                )

                            def test_unary_and_power(self) -> None:
                                self.assertEqual(
                                    self.engine.evaluate("-2 ** 3", scale=0),
                                    Decimal("-8"),
                                )

                            def test_division_by_zero_raises_domain_error(self) -> None:
                                with self.assertRaises(CalculatorDivisionByZeroError):
                                    self.engine.evaluate("5 / 0")

                            def test_rejects_invalid_syntax(self) -> None:
                                with self.assertRaises(CalculatorValidationError):
                                    self.engine.evaluate("import os")

                            def test_rejects_oversized_exponent(self) -> None:
                                with self.assertRaises(CalculatorValidationError):
                                    self.engine.evaluate("2 ** 42")

                            def test_rejects_malformed_expression(self) -> None:
                                with self.assertRaises(CalculatorSyntaxError):
                                    self.engine.evaluate("(2 + 3")


                        if __name__ == "__main__":
                            unittest.main()
                        """
                    ),
                ),
                (
                    "tests/test_cli.py",
                    _block(
                        """
                        from __future__ import annotations

                        import io
                        import sys
                        import unittest
                        from pathlib import Path

                        ROOT = Path(__file__).resolve().parents[1]
                        SRC = ROOT / "src"
                        if str(SRC) not in sys.path:
                            sys.path.insert(0, str(SRC))

                        from calculator.cli import run


                        class CalculatorCliTests(unittest.TestCase):
                            def test_run_success(self) -> None:
                                out = io.StringIO()
                                code = run(
                                    ["2", "+", "2", "*", "3", "--scale", "0"],
                                    stdout=out,
                                    stderr=io.StringIO(),
                                )
                                self.assertEqual(code, 0)
                                self.assertEqual(out.getvalue().strip(), "8")

                            def test_run_error(self) -> None:
                                err = io.StringIO()
                                code = run(["5", "/", "0"], stdout=io.StringIO(), stderr=err)
                                self.assertEqual(code, 1)
                                self.assertIn("Error:", err.getvalue())


                        if __name__ == "__main__":
                            unittest.main()
                        """
                    ),
                ),
            ),
        )

    def _generate_project_with_gemini(
        self,
        *,
        project_name: str,
        resolved_project_type: str,
        objective: str,
        fallback_template: ProjectTemplate,
    ) -> GeneratedProjectBundle | None:
        config = self._load_config()
        if config is None or not config.primary_llm_api_key():
            return None

        system_prompt = (
            "You generate production-ready starter projects as strict JSON. "
            "Return exactly one JSON object with keys: files (array) and summary (string). "
            "Each files item must be {\"path\": string, \"content\": string}. "
            "Use only relative paths and never use '..' segments or absolute paths. "
            "Prioritize modular architecture, type hints, strong error handling, and tests. "
            "Include pyproject.toml, README.md, and at least one unit test module. "
            "Keep output ASCII."
        )
        user_prompt = (
            f"Project name: {project_name}\n"
            f"Resolved project type: {resolved_project_type}\n"
            f"Objective: {objective}\n"
            "Generate 6 to 16 essential files with enterprise-level code quality."
        )

        try:
            raw = chat_complete(
                config,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.1,
                timeout=55,
                max_tokens=3500,
                response_format_json=True,
            )
        except Exception:
            return None

        payload = self._parse_json_object(raw)
        if not isinstance(payload, dict):
            return None

        files_payload = payload.get("files")
        if not isinstance(files_payload, list):
            return None

        collected: list[tuple[str, str]] = []
        seen_paths: set[str] = set()
        for item in files_payload:
            if not isinstance(item, dict):
                continue

            relative_path = self._sanitize_relative_path(str(item.get("path") or ""))
            if not relative_path:
                continue
            normalized_path = relative_path.lower()
            if normalized_path in seen_paths:
                continue
            seen_paths.add(normalized_path)

            content = str(item.get("content") or "")
            size = len(content.encode("utf-8", errors="ignore"))
            if size <= 0 or size > self._MAX_GENERATED_FILE_BYTES:
                continue

            collected.append((relative_path, content))
            if len(collected) >= self._MAX_GENERATED_FILES:
                break

        if not collected:
            return None

        if not self._is_generated_bundle_acceptable(collected, resolved_project_type=resolved_project_type):
            return None

        collected = self._apply_quality_baseline(collected, fallback_template=fallback_template)

        summary = str(payload.get("summary") or "").strip()
        return GeneratedProjectBundle(files=tuple(collected), summary=summary)

    def _is_generated_bundle_acceptable(
        self,
        files: list[tuple[str, str]],
        *,
        resolved_project_type: str,
    ) -> bool:
        if len(files) < 4:
            return False

        paths = [path for path, _content in files]
        has_readme = any(path.lower() == "readme.md" for path in paths)
        has_python = any(path.lower().endswith(".py") for path in paths)
        has_pyproject = any(path.lower() == "pyproject.toml" for path in paths)
        has_tests = any(path.lower().startswith("tests/") and path.lower().endswith(".py") for path in paths)
        if not (has_readme and has_python and has_pyproject and has_tests):
            return False

        if resolved_project_type == "python-cli" and len(files) < 6:
            return False

        if resolved_project_type == "fastapi-service":
            return any(path.lower().endswith("app/main.py") for path in paths)
        return True

    @staticmethod
    def _apply_quality_baseline(
        generated_files: list[tuple[str, str]],
        *,
        fallback_template: ProjectTemplate,
    ) -> list[tuple[str, str]]:
        merged = list(generated_files)
        merged_keys = {path.lower() for path, _content in merged}

        baseline_paths = {"readme.md", "pyproject.toml", "requirements.txt", ".gitignore", ".env.example"}
        for path, content in fallback_template.files:
            path_key = path.lower()
            if path_key in merged_keys:
                continue
            if path_key in baseline_paths:
                merged.append((path, content))
                merged_keys.add(path_key)

        return merged

    def _generate_plan_with_gemini(self, objective: str) -> list[str] | None:
        config = self._load_config()
        if config is None or not config.primary_llm_api_key():
            return None

        system_prompt = (
            "You create concise engineering implementation plans. "
            "Return strict JSON with one key: steps (array of strings). "
            "Generate 4 to 7 concrete steps."
        )

        try:
            raw = chat_complete(
                config,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": objective},
                ],
                temperature=0.15,
                timeout=25,
                max_tokens=700,
                response_format_json=True,
            )
        except Exception:
            return None

        payload = self._parse_json_object(raw)
        if not isinstance(payload, dict):
            return None

        steps_payload = payload.get("steps")
        if not isinstance(steps_payload, list):
            return None

        steps: list[str] = []
        for item in steps_payload:
            text = " ".join(str(item or "").split())
            if not text:
                continue
            steps.append(text)
            if len(steps) >= 7:
                break

        if len(steps) < 3:
            return None
        return steps

    @staticmethod
    def _extract_first_json_object(raw: str) -> str | None:
        source = str(raw or "").strip()
        if not source:
            return None

        if source.startswith("{") and source.endswith("}"):
            return source

        match = re.search(r"\{[\s\S]*\}", source)
        if match:
            return match.group(0)
        return None

    def _parse_json_object(self, raw: str) -> dict[str, Any] | None:
        candidate = self._extract_first_json_object(raw)
        if not candidate:
            return None

        try:
            payload = json.loads(candidate)
        except json.JSONDecodeError:
            return None

        if not isinstance(payload, dict):
            return None
        return payload

    @staticmethod
    def _sanitize_relative_path(raw_path: str) -> str:
        text = str(raw_path or "").strip().replace("\\", "/")
        if not text:
            return ""

        if re.match(r"^[a-zA-Z]:", text):
            return ""

        text = re.sub(r"/+", "/", text).lstrip("/")
        if not text:
            return ""

        posix = PurePosixPath(text)
        if posix.is_absolute():
            return ""

        parts = list(posix.parts)
        if not parts or any(part in {"", ".", ".."} for part in parts):
            return ""

        return "/".join(parts)

    def _resolve_target_root(self, raw_path: str) -> Path:
        candidate = Path(raw_path).expanduser() if raw_path else self._workspace_root
        if not candidate.is_absolute():
            return (self._workspace_root / candidate).resolve()
        return candidate.resolve()

    @staticmethod
    def _extract_quoted_path(text: str) -> str:
        source = str(text or "")
        if not source:
            return ""
        match = re.search(r"['\"]([^'\"]+)['\"]", source)
        if not match:
            return ""
        return str(match.group(1) or "").strip()

    def _infer_working_directory_from_request(self, request_text: str) -> Path:
        source = str(request_text or "")
        lowered = source.lower()

        quoted = self._extract_quoted_path(source)
        if quoted:
            candidate = self._resolve_target_root(quoted)
            if candidate.exists() and candidate.is_file():
                return candidate.parent
            if candidate.exists() and candidate.is_dir():
                return candidate

        home = Path.home()
        if re.search(r"\bdownloads?\b", lowered):
            candidate = (home / "Downloads").resolve()
            if candidate.exists():
                return candidate
        if re.search(r"\bdesktop\b", lowered):
            candidate = (home / "Desktop").resolve()
            if candidate.exists():
                return candidate
        if re.search(r"\b(my\s+documents?|documents?)\b", lowered):
            candidate = (home / "Documents").resolve()
            if candidate.exists():
                return candidate

        named_folder = re.search(
            r"\b(?:folder|directory)(?:\s+(?:named|called))?\s+([a-zA-Z0-9_.\\/-]{1,160})",
            source,
            flags=re.IGNORECASE,
        )
        if named_folder:
            text = str(named_folder.group(1) or "").strip(" .,!?;:\"'")
            if text:
                candidate = self._resolve_target_root(text)
                if candidate.exists() and candidate.is_dir():
                    return candidate

        return self._workspace_root

    @staticmethod
    def _extract_explicit_terminal_command(request_text: str) -> str:
        source = str(request_text or "").strip()
        if not source:
            return ""

        patterns = (
            r"\brun\s+(?:the\s+)?command\s+['\"]([^'\"]+)['\"]",
            r"\bexecute\s+['\"]([^'\"]+)['\"]",
            r"\bin\s+terminal\s+run\s+['\"]([^'\"]+)['\"]",
        )
        for pattern in patterns:
            match = re.search(pattern, source, flags=re.IGNORECASE)
            if not match:
                continue
            command = " ".join(str(match.group(1) or "").strip().split())
            if command:
                return command
        return ""

    def _infer_file_target_from_request(self, request_text: str, cwd: Path) -> Path | None:
        source = str(request_text or "")

        quoted = self._extract_quoted_path(source)
        if quoted:
            candidate = self._resolve_target_root(quoted)
            if candidate.exists() and candidate.is_file():
                return candidate

        inline = re.search(
            r"\b([a-zA-Z0-9_./\\-]+\.(?:py|js|ts|ps1|cmd|bat|sh|go|rb|java|jar))\b",
            source,
            flags=re.IGNORECASE,
        )
        if inline:
            token = str(inline.group(1) or "").strip()
            candidate = self._resolve_target_root(token)
            if candidate.exists() and candidate.is_file():
                return candidate
            relative = (cwd / token).resolve()
            if relative.exists() and relative.is_file():
                return relative

        hint_order = (
            "main.py",
            "app.py",
            "server.py",
            "manage.py",
            "index.js",
            "app.js",
            "main.js",
        )
        lowered = source.lower()
        if re.search(r"\b(run|execute|start)\b", lowered) and re.search(r"\b(file|script)\b", lowered):
            for name in hint_order:
                candidate = (cwd / name).resolve()
                if candidate.exists() and candidate.is_file():
                    return candidate

        return None

    @staticmethod
    def _build_file_execution_command(file_path: Path) -> str:
        target = Path(file_path)
        suffix = target.suffix.lower()
        quoted = f'"{str(target)}"'

        if suffix == ".py":
            return f"python {quoted}"
        if suffix == ".js":
            return f"node {quoted}"
        if suffix == ".ts":
            return f"npx ts-node {quoted}"
        if suffix == ".ps1":
            return f"powershell -NoProfile -ExecutionPolicy Bypass -File {quoted}"
        if suffix in {".cmd", ".bat"}:
            return f"cmd /c {quoted}"
        if suffix == ".sh":
            return f"bash {quoted}"
        if suffix == ".go":
            return f"go run {quoted}"
        if suffix == ".rb":
            return f"ruby {quoted}"
        if suffix == ".jar":
            return f"java -jar {quoted}"
        return ""

    def _infer_project_execution_command(self, project_root: Path, request_text: str) -> str:
        root = Path(project_root)
        lowered = str(request_text or "").lower()

        package_json = root / "package.json"
        if package_json.exists():
            scripts = self._read_npm_scripts(package_json)
            if "test" in lowered and "test" in scripts:
                return "npm test"
            if "build" in lowered and "build" in scripts:
                return "npm run build"
            if "dev" in scripts:
                return "npm run dev"
            if "start" in scripts:
                return "npm start"
            if "serve" in scripts:
                return "npm run serve"
            return "npm run dev"

        if (root / "manage.py").exists():
            return "python manage.py runserver"

        if (root / "Cargo.toml").exists():
            return "cargo run"

        if (root / "go.mod").exists():
            return "go run ."

        if list(root.glob("*.sln")) or list(root.glob("*.csproj")):
            return "dotnet run"

        if (root / "app" / "main.py").exists():
            if re.search(r"\bfastapi|uvicorn|api\b", lowered):
                return "python -m uvicorn app.main:app --reload"
            return "python app/main.py"

        if (root / "main.py").exists():
            return "python main.py"

        if (root / "app.py").exists():
            return "python app.py"

        if (root / "server.py").exists():
            return "python server.py"

        return ""

    @staticmethod
    def _read_npm_scripts(package_json: Path) -> set[str]:
        try:
            payload = json.loads(package_json.read_text(encoding="utf-8"))
        except Exception:
            return set()
        scripts = payload.get("scripts") if isinstance(payload, dict) else {}
        if not isinstance(scripts, dict):
            return set()
        return {str(key).strip().lower() for key in scripts.keys() if str(key).strip()}

    @classmethod
    def _normalize_dependency_name(cls, value: str) -> str:
        text = str(value or "").strip()
        if not text:
            return ""

        text = text.split(";", 1)[0].strip()
        text = text.split("[", 1)[0].strip()
        text = re.split(r"[<>=!~]", text, maxsplit=1)[0].strip()
        if not text:
            return ""

        return re.sub(r"[-_.]+", "-", text).lower()

    @classmethod
    def _parse_dependency_names_from_requirements(cls, text: str) -> set[str]:
        deps: set[str] = set()
        for raw_line in str(text or "").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith(("-r", "--", "-e", "git+", "http://", "https://")):
                continue
            name = cls._normalize_dependency_name(line)
            if name:
                deps.add(name)
        return deps

    @classmethod
    def _parse_dependency_names_from_setup(cls, text: str) -> set[str]:
        deps: set[str] = set()
        source = str(text or "")

        for block in re.findall(r"install_requires\s*=\s*\[(.*?)\]", source, flags=re.IGNORECASE | re.DOTALL):
            for item in re.findall(r"['\"]([^'\"]+)['\"]", block):
                name = cls._normalize_dependency_name(item)
                if name:
                    deps.add(name)

        return deps

    @classmethod
    def _parse_dependency_names_from_pyproject(cls, text: str) -> set[str]:
        source = str(text or "")

        try:
            try:
                import tomllib as _toml  # type: ignore[attr-defined]
            except Exception:
                import tomli as _toml  # type: ignore[import-not-found]

            payload = _toml.loads(source)
            project = payload.get("project") if isinstance(payload, dict) else {}
            deps_raw = project.get("dependencies") if isinstance(project, dict) else []
            optional = project.get("optional-dependencies") if isinstance(project, dict) else {}

            parsed: set[str] = set()
            if isinstance(deps_raw, list):
                for item in deps_raw:
                    name = cls._normalize_dependency_name(str(item or ""))
                    if name:
                        parsed.add(name)

            if isinstance(optional, dict):
                for items in optional.values():
                    if not isinstance(items, list):
                        continue
                    for item in items:
                        name = cls._normalize_dependency_name(str(item or ""))
                        if name:
                            parsed.add(name)

            if parsed:
                return parsed
        except Exception:
            pass

        # Regex fallback for environments without TOML parser support.
        deps: set[str] = set()
        for block in re.findall(r"dependencies\s*=\s*\[(.*?)\]", source, flags=re.IGNORECASE | re.DOTALL):
            for item in re.findall(r"['\"]([^'\"]+)['\"]", block):
                name = cls._normalize_dependency_name(item)
                if name:
                    deps.add(name)

        return deps

    @staticmethod
    def _sanitize_project_name(value: str) -> str:
        source = str(value or "").strip()
        if not source:
            return ""

        text = re.sub(r"[^a-zA-Z0-9_-]+", "-", source)
        text = re.sub(r"-{2,}", "-", text)
        text = text.strip("-_")
        if len(text) > 64:
            text = text[:64].rstrip("-_")
        return text

    @staticmethod
    def _error(error: str, message: str, *, details: dict[str, Any] | None = None) -> dict[str, Any]:
        return {
            "status": "error",
            "action": "coding_assist",
            "success": False,
            "verified": False,
            "error": error,
            "message": message,
            "details": details or {},
        }


def coding_assist_action(args: dict[str, Any], *, workspace_root: str) -> dict[str, Any]:
    """Registry adapter for coding assistant orchestration."""
    action = str(args.get("action") or "").strip().lower()
    service = CodingAssistService(workspace_root=workspace_root)

    raw_open_after_create = args.get("open_after_create")
    if raw_open_after_create is None:
        open_after_create = True
    elif isinstance(raw_open_after_create, bool):
        open_after_create = raw_open_after_create
    else:
        open_after_create = str(raw_open_after_create).strip().lower() in {"1", "true", "yes", "on"}

    if action in {"create_project", "scaffold"}:
        return service.create_project(
            name=str(args.get("name") or args.get("project_name") or ""),
            project_type=str(args.get("project_type") or "python-cli"),
            target_dir=str(args.get("target_dir") or CodingAssistService._DEFAULT_PROJECTS_DIR),
            objective=str(args.get("objective") or ""),
            prompt=str(args.get("prompt") or ""),
            open_after_create=open_after_create,
        )

    if action in {"create_files", "write_files"}:
        files = args.get("files") if isinstance(args.get("files"), list) else []
        return service.create_files(
            base_dir=str(args.get("base_dir") or "."),
            files=files,
        )

    if action in {"run_command", "command"}:
        return service.run_command(
            command=str(args.get("command") or "").strip(),
            cwd=str(args.get("cwd") or "."),
            timeout_seconds=int(args.get("timeout_seconds") or 90),
        )

    if action in {"run_file", "execute_file"}:
        return service.run_file(
            file_path=str(args.get("file_path") or args.get("path") or "").strip(),
            cwd=str(args.get("cwd") or "."),
            timeout_seconds=int(args.get("timeout_seconds") or 180),
        )

    if action in {"run_project", "start_project"}:
        raw_open_folder = args.get("open_folder")
        if isinstance(raw_open_folder, bool):
            open_folder = raw_open_folder
        else:
            open_folder = str(raw_open_folder or "").strip().lower() in {"1", "true", "yes", "on"}
        return service.run_project(
            project_path=str(args.get("project_path") or args.get("path") or "."),
            command=str(args.get("command") or "").strip(),
            open_folder=open_folder,
            timeout_seconds=int(args.get("timeout_seconds") or 240),
            request=str(args.get("request") or args.get("query") or ""),
        )

    if action in {"run_from_request", "run_request", "run"}:
        raw_open_folder = args.get("open_folder")
        if raw_open_folder is None:
            open_folder = True
        elif isinstance(raw_open_folder, bool):
            open_folder = raw_open_folder
        else:
            open_folder = str(raw_open_folder).strip().lower() in {"1", "true", "yes", "on"}
        return service.run_from_request(
            request=str(args.get("request") or args.get("query") or "").strip(),
            cwd=str(args.get("cwd") or "").strip() or None,
            open_folder=open_folder,
            timeout_seconds=int(args.get("timeout_seconds") or 240),
        )

    if action in {"plan", "plan_project"}:
        return service.plan(objective=str(args.get("objective") or args.get("prompt") or ""))

    if action in {"compare_dependencies", "dependency_diff", "compare_requirements"}:
        return service.compare_dependencies(
            requirements_path=str(args.get("requirements_path") or "requirements.txt"),
            setup_path=str(args.get("setup_path") or "setup.py"),
            pyproject_path=str(args.get("pyproject_path") or "pyproject.toml"),
        )

    # Convenience delegation to lower-level controllers.
    if action.startswith("file:"):
        delegated = dict(args)
        delegated["action"] = action.split(":", 1)[1].strip() or ""
        return file_control_action(delegated, workspace_root=workspace_root)

    if action.startswith("cmd:"):
        delegated = dict(args)
        delegated["action"] = action.split(":", 1)[1].strip() or "run"
        return cmd_control_action(delegated, workspace_root=workspace_root)

    return service._error(
        "unsupported_action",
        f"Unsupported coding_assist action: {action or '(empty)'}",
    )
